#Installing:
fedpkg
ansible-srpm-macros
bodhi-client
createrepo_c
createrepo_c-libs
dash
debugedit
devscripts-checkbashisms
drpm
dwz
ed
efi-srpm-macros
fakeroot
fakeroot-libs
fonts-srpm-macros
forge-srpm-macros
fpc-srpm-macros
ghc-srpm-macros
gnat-srpm-macros
go-srpm-macros
kernel-srpm-macros
koji
krb5-pkinit
krb5-workstation
libappstream-glib
libdnf5
libdnf5-cli
libgit2
libkadm5
llhttp
lua-srpm-macros
mock
mock-core-configs
mock-filesystem
ocaml-srpm-macros
openblas-srpm-macros
package-notes-srpm-macros
patch
perl-srpm-macros
pyproject-srpm-macros
python-srpm-macros
python3-GitPython
python3-authlib
python3-babel
python3-backoff
python3-bugzilla
python3-cccolutils
python3-click-plugins
python3-construct
python3-decorator
python3-defusedxml
python3-gitdb
python3-gssapi
python3-jinja2
python3-koji
python3-krb5
python3-libmodulemd
python3-munch
python3-openidc-client
python3-progressbar2
python3-pybeam
python3-pycurl
python3-pygit2
python3-pyroute2
python3-requests-gssapi
python3-requests-kerberos
python3-rpkg
python3-rpmautospec
python3-rpmautospec-core
python3-smmap
python3-spnego
python3-spnego+kerberos
python3-templated-dictionary
python3-tomli-w
python3-typing-extensions
python3-utils
python3-zstandard
qt5-srpm-macros
qt6-srpm-macros
redhat-rpm-config
rpkg-common
rpm-build
rpmautospec
rpmdevtools
rpmlint
rpmlint-fedora-license-data
rpmlint-fedora-license-data-legacy
rust-srpm-macros
sdbus-cpp
systemd-rpm-macros
zig-srpm-macros
zstd
nstalling
dnf-utils
dnf5
dnf5-plugins
fedora-packager
fedora-packager-kerberos

